<?php
        $query_string = $_SERVER['QUERY_STRING'];
?>


<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);

function goBack() {
    window.history.back();
}


</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Report Web      <small><?= cclang('detail', ['Report Web']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/report_web?'.$query_string); ?>">Report Web</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Report Web</h3>
                     <h5 class="widget-user-desc">Detail Report Web</h5>
                     <hr>
                  </div>


		<div class="widget-user-header ">
                                <ul class="nav nav-pills">
		
				
					<?php if(!empty($_GET['go_back'])) { ?>
                                        <a class="btn btn-sm btn-success" href="#" onclick="goBack()"><?= $_GET['go_back']; ?></a>
                                <?php } ?>
                                 </ul>
                        </div>




                 
                  <div class="form-horizontal" name="form_report_web" id="form_report_web" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Report Name </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->report_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Table Name </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->table_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Parent Report Id </label>

                        <div class="col-sm-8">
				<a style="text-decoration: underline;" class="label-default" href='<?= site_url("administrator/report_web/view/{$report_web->tab_parent_report_id_value }"); ?>'>
                           <?= _ent($report_web->tab_parent_report_id_label); ?>
				</a>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Icon </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->icon); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Sequence </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->sequence); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2">Columns </label>

                        <div class="col-sm-8">
                           <?= _ent($report_web->columns); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('report_web_update', function() use ($report_web){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit report_web (Ctrl+e)" href="<?= site_url('administrator/report_web/edit/'.$report_web->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update'); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/report_web/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_back_button'); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
