<style>
.chosen-container
{
    width: 100% !important;
}
</style>

<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
	// Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Report_web/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);

function goBack() {
    window.history.back();
}

</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      <?= $heading ?>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= $heading ?></li>
   </ol>
</section>


<section class="content">
<div class="row">
	<?php foreach($report_list as $rep) { ?>

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="info-box button" onclick="goUrl('administrator/report_master/view/<?= $rep->id ?>')">
                <span class="info-box-icon bg-black">
                    <i class="<?= $rep->icon ?>">
                    </i>
		</span>
		<div class="info-box button" onclick="goUrl('administrator/report_master/view/<?= $rep->id ?>')">
                	<div class="info-box-content">
                    		<span class="info-box-text">
                        		<?= $rep->report_name ?>
                    		</span>
                	</div>
            	</div>
            </div>
        </div>
	<?php } ?>
</div>

<div class="row">
        <?php foreach($report_list as $rep) { ?>

	<div class="col-md-6 col-sm-12 col-xs-12">
			<?php if(!empty($rep->columns)) { ?>
 			<div class="info-box">
                                <span class="info-box-icon bg-yello"><i class="<?= $rep->icon ?>"></i></span>
                                <div class="info-box-content">
					<span class="info-box-text">
						<?= $rep->report_name ?>
					</span>
					<hr>
				</div>

<?php
						$query = $this->db->query("SELECT {$rep->columns} FROM {$rep->table_name} LIMIT 5 ");
?>
				<table class="table">
                                        <thead>
						<th>#</th>
						<?php foreach(explode(",", $rep->columns) as $col) { ?>
						<th><?= str_replace("_", " ", $col) ?> </th>
						<?php } ?>
                                        </thead>
                                        <tbody>
                                                <?php $i=1;
                                                        foreach($query->result() as $row) {
                                                                echo "<tr>";
								echo "<td>$i</td>";
								foreach(explode(",", $rep->columns) as $col) {
									$col = trim($col);
									echo "<td> {$row->$col}</td>";
								}
                                                                echo "</tr>";
                                                                $i++;
                                                        }
?>
					</tbody>
				</table>
						 <center><button class="btn btn-blk btn-raised" onclick="goUrl('administrator/report_master/view/<?= $rep->id ?>')">See More</button></center>
				<br>

			</div>	
			<?php  } ?>



        </div>
        <?php } ?>
</div>


</section>
<!-- /.content -->

